<a href="https://colab.research.google.com/github/onmyeoin/tensorflow/blob/main/00_intro_to_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.11.0


In [2]:
# Creating tensor with tf.constant

scaler = tf.constant(7)
scaler


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scaler.ndim

0

In [5]:
# Create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check dimension of vector

vector.ndim

1

In [8]:
# create a matrix

matrix = tf.constant([[10,7], [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [11]:
# another matrix

another_matrix = tf.constant([[10.,7.], [9.,20.], [8.,9.]], dtype =tf.float16)


another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 9., 20.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [13]:
# lets create a tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

definitions

* Scalar = a singal number
* Vector = a number with direction
* matrix = a 2 dimentional array of numbers
* Vector = an n-dimentional array of numbers

In [15]:
Creating tensors with `tf.variable`

SyntaxError: ignored

In [16]:
# Create same tensor as above using tf.Variable()

changeable_tensor = tf.Variable([10,7])

unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor



(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:
# use .assign to change varibale
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
# cannot change variable in tf.constant

unchangeable_tensor[0].assign(7)

AttributeError: ignored

### Creating Random Tensors



In [22]:
# create two random, but the same tensors

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [30]:
# shuffle a tensor (valuable for when you want to shuffle data so that the inherent order doesnt affect learning)

not_shuffled = tf.constant([[10,2],
                           [3,4],
                           [12,13]])

# Shuffle our non-shuffled tensor

tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [12, 13],
       [10,  2]], dtype=int32)>

In [36]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [12, 13],
       [10,  2]], dtype=int32)>

In [29]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  2],
       [ 3,  4],
       [12, 13]], dtype=int32)>

### Other ways to make Tensors

In [37]:
# create tensor of all ones
tf.ones([10,7])


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [38]:
# create tensor of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Change numpy array into tensors

The main difference between numpy arrays and tensors is that tensors can be run on GPU/TPU

In [39]:
# change numpy array into tensor

import numpy as np
numpy_a = np.arange(1,25, dtype=np.int32)

numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [40]:
# can pass any numpy array to tf.constant to create a tensor
A = tf.constant(numpy_a)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [42]:
# Can chnage shape of tensor as long as the number of elements are equal
B = tf.constant(numpy_a, shape=(2,3,4))
B


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting more informations from tensors

In [43]:
# rank = dimensions (rank 4 = 4 dimensions)

rank_4 = tf.zeros(shape=(2,3,4,5))
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [44]:
rank_4.shape, rank_4.ndim, tf.size(rank_4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [45]:
# Get various attributes of tensor
print("Datatype of every element: ", rank_4.dtype)
print("Number of Dimensions (rank): ", rank_4.ndim)
print("Shape of tensor: ",rank_4.shape)
print("Elements along 0 axis: ", rank_4.shape[0])
print("Elements along the last axis: ", rank_4.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4))

Datatype of every element:  <dtype: 'float32'>
Number of Dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)


### Indexing Tensors

Tensors can be indexed like a python list

In [47]:
# Get first two elements of each dimension
rank_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [48]:
# Get first element from each dimension from each index except the final one

rank_4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [49]:
# Cret a rank 2 tensor

rank_2_tensor = tf.constant([[10,7],[2,3]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [50]:
# Get last item of each row from rank 2 tensor
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3]], dtype=int32)>

In [51]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [52]:
# Add in extra dimension to our tensor (tf.newaxis)
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [53]:
# alternative method of adding new dimension 
tf.expand_dims(rank_2_tensor,axis=-1)  #-> expands the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [54]:
# expand the 0 axis

tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 2,  3]]], dtype=int32)>

### Manipulating Tensors (tensor operations)

In [56]:
# basic operations
tensor = tf.constant([[10,7],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [57]:
# can add using the + operation
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [58]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [59]:
# multiplcation also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [62]:
# there are also tensorflow built in functions

tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [63]:
tf.math.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# tensorflows built in operations are much faster than equivilent python opertions

### Matrix Multiplications

in ML Matrix Multiplication is one of the ost common tensor operations

a dot product is used to multiply one matrix by another matrix

There are two rules required for Matrix multiplication

1) the inner dimensions must match

2) The resulting matrix is the same shape as the inner matrix


In [64]:
# matrix multiplication tnesorflow

print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [65]:
# tf.matmul 
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [66]:
# Can use the python matric multilcation operator @

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [67]:
# Multiplying tensors of different shapes

# Creating a 3,2 tensor

X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

# Create another 3,2 tensor

Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [68]:
# Matrix Multiply 

X @ Y

InvalidArgumentError: ignored

In [74]:
# currently inner dimensions do not match so matrix multiplication will not work
X.shape,Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [78]:
# to get aorund this, we reshape the matrix
tf.reshape(Y,(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [79]:
# Now we can see that the inner dimensions do match
X.shape, tf.reshape(Y,(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [80]:
# Now we can do matrix multiplication

X @ tf.reshape(Y,(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [81]:
# changing shape of X instead of Y will change outcome

tf.reshape(X,(2,3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [83]:
# This is because the resulting matrix will be the shape of the outer dimensions (in this case 2,2)
tf.reshape(X, (2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [84]:
# Can do the same with transpose, although transpose flips the entire matrix on its axis whereas reshape just reshuffles 

tf.transpose(X), tf.reshape(X,(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

### The Dot Product

Can perform matrix multiplication using:

* `tf.matmul(X,Y)`
* `tf.tensordot(X,Y)`

In [85]:
# Perform the dot product on X and Y (requires X or Y to be transposed)

tf.tensordot(tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [88]:
# difference between dot product of X and Y transposed vs reshape

tf.matmul(X,tf.reshape(Y,(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [89]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

### Changing the datatype of a tensor

Can be useful to change dtype as some types take up less memory and can improve performace (int32 -> int16)

In [90]:
# Create a ne tensor with a default datatype

B = tf.constant([1.7,1.3])
B.dtype

tf.float32

In [92]:
C = tf.constant([2,3])
C.dtype

tf.int32

In [95]:
# Change from float32 to float16 (Reduced precision -> runs faster on modern hardware -> less memory)

D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 1.3], dtype=float16)>,
 tf.float16)

In [98]:
# Change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

### Aggregating Tensors

In [3]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [4]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

from tensorflow.python.ops.math_ops import Sum
Other forms of aggregations:
* Min
* Max
* Sum
* Mean

In [8]:
# Create a large tensor
import numpy as np

E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([58, 55, 47, 83, 96, 74, 17, 23, 67, 66, 70, 11, 43, 27, 27, 85, 77,
       12,  3, 54, 82,  0, 21, 22,  4, 39, 39, 84, 38, 75, 51, 25, 21, 76,
       10, 34, 86, 73,  0, 64, 40, 92,  2,  3, 33, 27, 76, 28, 15,  4])>

In [9]:
# Find Min

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [10]:
# find max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [11]:
# find mean

tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [12]:
# find sum

tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2159>

### Finding Positonal Min and Max

Useful when looking at prediction probabilities output from NN

In [13]:
# Create new tensor for finding positional max and min
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [14]:
# find positional max (argmax)

tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [15]:
# index on our largest value

F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [16]:
# find value of F

tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

### Squeezing a tensor (removing all dimensions of size 1)


In [25]:
# Create a tensor

tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [26]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [30]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

### One Hot Encoding

In [34]:
# Create list of indices (could be anything)

some_list = [0,1,2,3,4] # could be red, blue, green, yellow, purple

# One hot encode our list

tf.one_hot(some_list, depth=5)


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>